### ISSUE TITLE
False-positives with tests usages

### ISSUE THREAD

**Issue by maks-rafalko** [shipmonk-rnd/dead-code-detector#209]
Hello, thanks for this package.

I try to introduce it to Infection here https://github.com/infection/infection/pull/2090, however there is a problem: code that is used **only** in tests [gives errors](https://github.com/infection/infection/actions/runs/15083507533/job/42403208118?pr=2090#step:7:123), while (from what I understood reading the docs) it shouldn't.

For example:

https://github.com/infection/infection/blob/469be21bf55197d03486a1180a735e915980c79e/src/TestFramework/Coverage/JUnit/JUnitTestCaseSorter.php#L53

this constant `BUCKETS_COUNT` is only used in 1 place - in tests here:

https://github.com/infection/infection/blob/3d6b2b2644e156dc51cb8699b422ad9ec3b0c343/tests/phpunit/TestFramework/Coverage/JUnit/JUnitTestCaseSorterTest.php#L114

But it's being reported:

```
 ------ ---------------------------------------------------------------------------------- 
  Line   TestFramework/Coverage/JUnit/JUnitTestCaseSorter.php                              
 ------ ---------------------------------------------------------------------------------- 
  53     Unused Infection\TestFramework\Coverage\JUnit\JUnitTestCaseSorter::BUCKETS_COUNT  
         🪪  shipmonk.deadConstant                                                         
 ------ ---------------------------------------------------------------------------------- 
```

Questions:

1. Am I right that this should **not** be reported by default? (so tests usages counts)
2. did I miss something in the configuration?

I tried some configuration adjustments, like explicitly enable `phpunit` 

```yaml
parameters:
    shipmonkDeadCode:
        usageProviders:
            phpunit:
                enabled: true
```

or explicitly disable tests excluder:

```yaml
parameters:
    shipmonkDeadCode:
        usageExcluders:
            tests:
                enabled: false
```

but this didn't help.

Potential issue is that our tests are located in `tests/phpunit` and in composer.json we have

```
"autoload-dev": {
        "psr-4": {
            "Infection\\Tests\\": "tests/phpunit"
        },
```

Thank you.
