### ISSUE TITLE
Detect `Symfony\Component\Console\Attribute\AsCommand` attribute as entry point

### ISSUE THREAD

**Issue by ruudk** [shipmonk-rnd/dead-code-detector#84]
It should not complain about the constructor.

**Comment by janedbal** [comment]
Shouldnt such command be still registered in DIC (which is detected)?

```yaml
services:
  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags:
        - console.command
  
  ShipMonk\SomeCommand:
```
