### ISSUE TITLE
Detect `Symfony\Component\HttpKernel\Controller\ValueResolverInterface` as entry point

### ISSUE THREAD

**Issue by ruudk** [shipmonk-rnd/dead-code-detector#85]

**Comment by janedbal** [comment]
How did you register such resolver? I thought you need to have it in DIC (which is detected):

```yaml
services:
  ShipMonk\InputMapper\InputArgumentValueResolver:
    tags:
      -
        name: controller.argument_value_resolver
```
